# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /src/myfork/vamp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /src/myfork/vamp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /src/myfork/vamp/CMakeFiles /src/myfork/vamp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /src/myfork/vamp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simdxorshift

# Build rule for target.
simdxorshift: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simdxorshift
.PHONY : simdxorshift

# fast build rule for target.
simdxorshift/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdxorshift.dir/build.make CMakeFiles/simdxorshift.dir/build
.PHONY : simdxorshift/fast

#=============================================================================
# Target rules for targets named _core_ext

# Build rule for target.
_core_ext: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _core_ext
.PHONY : _core_ext

# fast build rule for target.
_core_ext/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/build
.PHONY : _core_ext/fast

#=============================================================================
# Target rules for targets named nanobind-static-abi3

# Build rule for target.
nanobind-static-abi3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanobind-static-abi3
.PHONY : nanobind-static-abi3

# fast build rule for target.
nanobind-static-abi3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/build
.PHONY : nanobind-static-abi3/fast

#=============================================================================
# Target rules for targets named vamp_stub

# Build rule for target.
vamp_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_stub
.PHONY : vamp_stub

# fast build rule for target.
vamp_stub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_stub.dir/build.make CMakeFiles/vamp_stub.dir/build
.PHONY : vamp_stub/fast

#=============================================================================
# Target rules for targets named vamp_sphere_stub

# Build rule for target.
vamp_sphere_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_sphere_stub
.PHONY : vamp_sphere_stub

# fast build rule for target.
vamp_sphere_stub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_sphere_stub.dir/build.make CMakeFiles/vamp_sphere_stub.dir/build
.PHONY : vamp_sphere_stub/fast

#=============================================================================
# Target rules for targets named vamp_ur5_stub

# Build rule for target.
vamp_ur5_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_ur5_stub
.PHONY : vamp_ur5_stub

# fast build rule for target.
vamp_ur5_stub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_ur5_stub.dir/build.make CMakeFiles/vamp_ur5_stub.dir/build
.PHONY : vamp_ur5_stub/fast

#=============================================================================
# Target rules for targets named vamp_panda_stub

# Build rule for target.
vamp_panda_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_panda_stub
.PHONY : vamp_panda_stub

# fast build rule for target.
vamp_panda_stub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_panda_stub.dir/build.make CMakeFiles/vamp_panda_stub.dir/build
.PHONY : vamp_panda_stub/fast

#=============================================================================
# Target rules for targets named vamp_fetch_stub

# Build rule for target.
vamp_fetch_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_fetch_stub
.PHONY : vamp_fetch_stub

# fast build rule for target.
vamp_fetch_stub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_fetch_stub.dir/build.make CMakeFiles/vamp_fetch_stub.dir/build
.PHONY : vamp_fetch_stub/fast

#=============================================================================
# Target rules for targets named vamp_baxter_stub

# Build rule for target.
vamp_baxter_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_baxter_stub
.PHONY : vamp_baxter_stub

# fast build rule for target.
vamp_baxter_stub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_baxter_stub.dir/build.make CMakeFiles/vamp_baxter_stub.dir/build
.PHONY : vamp_baxter_stub/fast

#=============================================================================
# Target rules for targets named vamp_bimanualpanda_stub

# Build rule for target.
vamp_bimanualpanda_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_bimanualpanda_stub
.PHONY : vamp_bimanualpanda_stub

# fast build rule for target.
vamp_bimanualpanda_stub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_bimanualpanda_stub.dir/build.make CMakeFiles/vamp_bimanualpanda_stub.dir/build
.PHONY : vamp_bimanualpanda_stub/fast

#=============================================================================
# Target rules for targets named com_constraint

# Build rule for target.
com_constraint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 com_constraint
.PHONY : com_constraint

# fast build rule for target.
com_constraint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/com_constraint.dir/build.make CMakeFiles/com_constraint.dir/build
.PHONY : com_constraint/fast

#=============================================================================
# Target rules for targets named vamp_com_constraint_example

# Build rule for target.
vamp_com_constraint_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vamp_com_constraint_example
.PHONY : vamp_com_constraint_example

# fast build rule for target.
vamp_com_constraint_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_com_constraint_example.dir/build.make CMakeFiles/vamp_com_constraint_example.dir/build
.PHONY : vamp_com_constraint_example/fast

_deps/nanobind-src/src/common.o: _deps/nanobind-src/src/common.cpp.o
.PHONY : _deps/nanobind-src/src/common.o

# target to build an object file
_deps/nanobind-src/src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/common.cpp.o
.PHONY : _deps/nanobind-src/src/common.cpp.o

_deps/nanobind-src/src/common.i: _deps/nanobind-src/src/common.cpp.i
.PHONY : _deps/nanobind-src/src/common.i

# target to preprocess a source file
_deps/nanobind-src/src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/common.cpp.i
.PHONY : _deps/nanobind-src/src/common.cpp.i

_deps/nanobind-src/src/common.s: _deps/nanobind-src/src/common.cpp.s
.PHONY : _deps/nanobind-src/src/common.s

# target to generate assembly for a file
_deps/nanobind-src/src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/common.cpp.s
.PHONY : _deps/nanobind-src/src/common.cpp.s

_deps/nanobind-src/src/error.o: _deps/nanobind-src/src/error.cpp.o
.PHONY : _deps/nanobind-src/src/error.o

# target to build an object file
_deps/nanobind-src/src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/error.cpp.o
.PHONY : _deps/nanobind-src/src/error.cpp.o

_deps/nanobind-src/src/error.i: _deps/nanobind-src/src/error.cpp.i
.PHONY : _deps/nanobind-src/src/error.i

# target to preprocess a source file
_deps/nanobind-src/src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/error.cpp.i
.PHONY : _deps/nanobind-src/src/error.cpp.i

_deps/nanobind-src/src/error.s: _deps/nanobind-src/src/error.cpp.s
.PHONY : _deps/nanobind-src/src/error.s

# target to generate assembly for a file
_deps/nanobind-src/src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/error.cpp.s
.PHONY : _deps/nanobind-src/src/error.cpp.s

_deps/nanobind-src/src/implicit.o: _deps/nanobind-src/src/implicit.cpp.o
.PHONY : _deps/nanobind-src/src/implicit.o

# target to build an object file
_deps/nanobind-src/src/implicit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/implicit.cpp.o
.PHONY : _deps/nanobind-src/src/implicit.cpp.o

_deps/nanobind-src/src/implicit.i: _deps/nanobind-src/src/implicit.cpp.i
.PHONY : _deps/nanobind-src/src/implicit.i

# target to preprocess a source file
_deps/nanobind-src/src/implicit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/implicit.cpp.i
.PHONY : _deps/nanobind-src/src/implicit.cpp.i

_deps/nanobind-src/src/implicit.s: _deps/nanobind-src/src/implicit.cpp.s
.PHONY : _deps/nanobind-src/src/implicit.s

# target to generate assembly for a file
_deps/nanobind-src/src/implicit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/implicit.cpp.s
.PHONY : _deps/nanobind-src/src/implicit.cpp.s

_deps/nanobind-src/src/nb_enum.o: _deps/nanobind-src/src/nb_enum.cpp.o
.PHONY : _deps/nanobind-src/src/nb_enum.o

# target to build an object file
_deps/nanobind-src/src/nb_enum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_enum.cpp.o
.PHONY : _deps/nanobind-src/src/nb_enum.cpp.o

_deps/nanobind-src/src/nb_enum.i: _deps/nanobind-src/src/nb_enum.cpp.i
.PHONY : _deps/nanobind-src/src/nb_enum.i

# target to preprocess a source file
_deps/nanobind-src/src/nb_enum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_enum.cpp.i
.PHONY : _deps/nanobind-src/src/nb_enum.cpp.i

_deps/nanobind-src/src/nb_enum.s: _deps/nanobind-src/src/nb_enum.cpp.s
.PHONY : _deps/nanobind-src/src/nb_enum.s

# target to generate assembly for a file
_deps/nanobind-src/src/nb_enum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_enum.cpp.s
.PHONY : _deps/nanobind-src/src/nb_enum.cpp.s

_deps/nanobind-src/src/nb_ft.o: _deps/nanobind-src/src/nb_ft.cpp.o
.PHONY : _deps/nanobind-src/src/nb_ft.o

# target to build an object file
_deps/nanobind-src/src/nb_ft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_ft.cpp.o
.PHONY : _deps/nanobind-src/src/nb_ft.cpp.o

_deps/nanobind-src/src/nb_ft.i: _deps/nanobind-src/src/nb_ft.cpp.i
.PHONY : _deps/nanobind-src/src/nb_ft.i

# target to preprocess a source file
_deps/nanobind-src/src/nb_ft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_ft.cpp.i
.PHONY : _deps/nanobind-src/src/nb_ft.cpp.i

_deps/nanobind-src/src/nb_ft.s: _deps/nanobind-src/src/nb_ft.cpp.s
.PHONY : _deps/nanobind-src/src/nb_ft.s

# target to generate assembly for a file
_deps/nanobind-src/src/nb_ft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_ft.cpp.s
.PHONY : _deps/nanobind-src/src/nb_ft.cpp.s

_deps/nanobind-src/src/nb_func.o: _deps/nanobind-src/src/nb_func.cpp.o
.PHONY : _deps/nanobind-src/src/nb_func.o

# target to build an object file
_deps/nanobind-src/src/nb_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_func.cpp.o
.PHONY : _deps/nanobind-src/src/nb_func.cpp.o

_deps/nanobind-src/src/nb_func.i: _deps/nanobind-src/src/nb_func.cpp.i
.PHONY : _deps/nanobind-src/src/nb_func.i

# target to preprocess a source file
_deps/nanobind-src/src/nb_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_func.cpp.i
.PHONY : _deps/nanobind-src/src/nb_func.cpp.i

_deps/nanobind-src/src/nb_func.s: _deps/nanobind-src/src/nb_func.cpp.s
.PHONY : _deps/nanobind-src/src/nb_func.s

# target to generate assembly for a file
_deps/nanobind-src/src/nb_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_func.cpp.s
.PHONY : _deps/nanobind-src/src/nb_func.cpp.s

_deps/nanobind-src/src/nb_internals.o: _deps/nanobind-src/src/nb_internals.cpp.o
.PHONY : _deps/nanobind-src/src/nb_internals.o

# target to build an object file
_deps/nanobind-src/src/nb_internals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_internals.cpp.o
.PHONY : _deps/nanobind-src/src/nb_internals.cpp.o

_deps/nanobind-src/src/nb_internals.i: _deps/nanobind-src/src/nb_internals.cpp.i
.PHONY : _deps/nanobind-src/src/nb_internals.i

# target to preprocess a source file
_deps/nanobind-src/src/nb_internals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_internals.cpp.i
.PHONY : _deps/nanobind-src/src/nb_internals.cpp.i

_deps/nanobind-src/src/nb_internals.s: _deps/nanobind-src/src/nb_internals.cpp.s
.PHONY : _deps/nanobind-src/src/nb_internals.s

# target to generate assembly for a file
_deps/nanobind-src/src/nb_internals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_internals.cpp.s
.PHONY : _deps/nanobind-src/src/nb_internals.cpp.s

_deps/nanobind-src/src/nb_ndarray.o: _deps/nanobind-src/src/nb_ndarray.cpp.o
.PHONY : _deps/nanobind-src/src/nb_ndarray.o

# target to build an object file
_deps/nanobind-src/src/nb_ndarray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_ndarray.cpp.o
.PHONY : _deps/nanobind-src/src/nb_ndarray.cpp.o

_deps/nanobind-src/src/nb_ndarray.i: _deps/nanobind-src/src/nb_ndarray.cpp.i
.PHONY : _deps/nanobind-src/src/nb_ndarray.i

# target to preprocess a source file
_deps/nanobind-src/src/nb_ndarray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_ndarray.cpp.i
.PHONY : _deps/nanobind-src/src/nb_ndarray.cpp.i

_deps/nanobind-src/src/nb_ndarray.s: _deps/nanobind-src/src/nb_ndarray.cpp.s
.PHONY : _deps/nanobind-src/src/nb_ndarray.s

# target to generate assembly for a file
_deps/nanobind-src/src/nb_ndarray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_ndarray.cpp.s
.PHONY : _deps/nanobind-src/src/nb_ndarray.cpp.s

_deps/nanobind-src/src/nb_static_property.o: _deps/nanobind-src/src/nb_static_property.cpp.o
.PHONY : _deps/nanobind-src/src/nb_static_property.o

# target to build an object file
_deps/nanobind-src/src/nb_static_property.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_static_property.cpp.o
.PHONY : _deps/nanobind-src/src/nb_static_property.cpp.o

_deps/nanobind-src/src/nb_static_property.i: _deps/nanobind-src/src/nb_static_property.cpp.i
.PHONY : _deps/nanobind-src/src/nb_static_property.i

# target to preprocess a source file
_deps/nanobind-src/src/nb_static_property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_static_property.cpp.i
.PHONY : _deps/nanobind-src/src/nb_static_property.cpp.i

_deps/nanobind-src/src/nb_static_property.s: _deps/nanobind-src/src/nb_static_property.cpp.s
.PHONY : _deps/nanobind-src/src/nb_static_property.s

# target to generate assembly for a file
_deps/nanobind-src/src/nb_static_property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_static_property.cpp.s
.PHONY : _deps/nanobind-src/src/nb_static_property.cpp.s

_deps/nanobind-src/src/nb_type.o: _deps/nanobind-src/src/nb_type.cpp.o
.PHONY : _deps/nanobind-src/src/nb_type.o

# target to build an object file
_deps/nanobind-src/src/nb_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_type.cpp.o
.PHONY : _deps/nanobind-src/src/nb_type.cpp.o

_deps/nanobind-src/src/nb_type.i: _deps/nanobind-src/src/nb_type.cpp.i
.PHONY : _deps/nanobind-src/src/nb_type.i

# target to preprocess a source file
_deps/nanobind-src/src/nb_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_type.cpp.i
.PHONY : _deps/nanobind-src/src/nb_type.cpp.i

_deps/nanobind-src/src/nb_type.s: _deps/nanobind-src/src/nb_type.cpp.s
.PHONY : _deps/nanobind-src/src/nb_type.s

# target to generate assembly for a file
_deps/nanobind-src/src/nb_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/nb_type.cpp.s
.PHONY : _deps/nanobind-src/src/nb_type.cpp.s

_deps/nanobind-src/src/trampoline.o: _deps/nanobind-src/src/trampoline.cpp.o
.PHONY : _deps/nanobind-src/src/trampoline.o

# target to build an object file
_deps/nanobind-src/src/trampoline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/trampoline.cpp.o
.PHONY : _deps/nanobind-src/src/trampoline.cpp.o

_deps/nanobind-src/src/trampoline.i: _deps/nanobind-src/src/trampoline.cpp.i
.PHONY : _deps/nanobind-src/src/trampoline.i

# target to preprocess a source file
_deps/nanobind-src/src/trampoline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/trampoline.cpp.i
.PHONY : _deps/nanobind-src/src/trampoline.cpp.i

_deps/nanobind-src/src/trampoline.s: _deps/nanobind-src/src/trampoline.cpp.s
.PHONY : _deps/nanobind-src/src/trampoline.s

# target to generate assembly for a file
_deps/nanobind-src/src/trampoline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static-abi3.dir/build.make CMakeFiles/nanobind-static-abi3.dir/_deps/nanobind-src/src/trampoline.cpp.s
.PHONY : _deps/nanobind-src/src/trampoline.cpp.s

_deps/simdxorshift-src/src/simdxorshift128plus.o: _deps/simdxorshift-src/src/simdxorshift128plus.c.o
.PHONY : _deps/simdxorshift-src/src/simdxorshift128plus.o

# target to build an object file
_deps/simdxorshift-src/src/simdxorshift128plus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdxorshift.dir/build.make CMakeFiles/simdxorshift.dir/_deps/simdxorshift-src/src/simdxorshift128plus.c.o
.PHONY : _deps/simdxorshift-src/src/simdxorshift128plus.c.o

_deps/simdxorshift-src/src/simdxorshift128plus.i: _deps/simdxorshift-src/src/simdxorshift128plus.c.i
.PHONY : _deps/simdxorshift-src/src/simdxorshift128plus.i

# target to preprocess a source file
_deps/simdxorshift-src/src/simdxorshift128plus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdxorshift.dir/build.make CMakeFiles/simdxorshift.dir/_deps/simdxorshift-src/src/simdxorshift128plus.c.i
.PHONY : _deps/simdxorshift-src/src/simdxorshift128plus.c.i

_deps/simdxorshift-src/src/simdxorshift128plus.s: _deps/simdxorshift-src/src/simdxorshift128plus.c.s
.PHONY : _deps/simdxorshift-src/src/simdxorshift128plus.s

# target to generate assembly for a file
_deps/simdxorshift-src/src/simdxorshift128plus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdxorshift.dir/build.make CMakeFiles/simdxorshift.dir/_deps/simdxorshift-src/src/simdxorshift128plus.c.s
.PHONY : _deps/simdxorshift-src/src/simdxorshift128plus.c.s

_deps/simdxorshift-src/src/xorshift128plus.o: _deps/simdxorshift-src/src/xorshift128plus.c.o
.PHONY : _deps/simdxorshift-src/src/xorshift128plus.o

# target to build an object file
_deps/simdxorshift-src/src/xorshift128plus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdxorshift.dir/build.make CMakeFiles/simdxorshift.dir/_deps/simdxorshift-src/src/xorshift128plus.c.o
.PHONY : _deps/simdxorshift-src/src/xorshift128plus.c.o

_deps/simdxorshift-src/src/xorshift128plus.i: _deps/simdxorshift-src/src/xorshift128plus.c.i
.PHONY : _deps/simdxorshift-src/src/xorshift128plus.i

# target to preprocess a source file
_deps/simdxorshift-src/src/xorshift128plus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdxorshift.dir/build.make CMakeFiles/simdxorshift.dir/_deps/simdxorshift-src/src/xorshift128plus.c.i
.PHONY : _deps/simdxorshift-src/src/xorshift128plus.c.i

_deps/simdxorshift-src/src/xorshift128plus.s: _deps/simdxorshift-src/src/xorshift128plus.c.s
.PHONY : _deps/simdxorshift-src/src/xorshift128plus.s

# target to generate assembly for a file
_deps/simdxorshift-src/src/xorshift128plus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdxorshift.dir/build.make CMakeFiles/simdxorshift.dir/_deps/simdxorshift-src/src/xorshift128plus.c.s
.PHONY : _deps/simdxorshift-src/src/xorshift128plus.c.s

baxter.o: baxter.cc.o
.PHONY : baxter.o

# target to build an object file
baxter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/baxter.cc.o
.PHONY : baxter.cc.o

baxter.i: baxter.cc.i
.PHONY : baxter.i

# target to preprocess a source file
baxter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/baxter.cc.i
.PHONY : baxter.cc.i

baxter.s: baxter.cc.s
.PHONY : baxter.s

# target to generate assembly for a file
baxter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/baxter.cc.s
.PHONY : baxter.cc.s

bimanualpanda.o: bimanualpanda.cc.o
.PHONY : bimanualpanda.o

# target to build an object file
bimanualpanda.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/bimanualpanda.cc.o
.PHONY : bimanualpanda.cc.o

bimanualpanda.i: bimanualpanda.cc.i
.PHONY : bimanualpanda.i

# target to preprocess a source file
bimanualpanda.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/bimanualpanda.cc.i
.PHONY : bimanualpanda.cc.i

bimanualpanda.s: bimanualpanda.cc.s
.PHONY : bimanualpanda.s

# target to generate assembly for a file
bimanualpanda.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/bimanualpanda.cc.s
.PHONY : bimanualpanda.cc.s

fetch.o: fetch.cc.o
.PHONY : fetch.o

# target to build an object file
fetch.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/fetch.cc.o
.PHONY : fetch.cc.o

fetch.i: fetch.cc.i
.PHONY : fetch.i

# target to preprocess a source file
fetch.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/fetch.cc.i
.PHONY : fetch.cc.i

fetch.s: fetch.cc.s
.PHONY : fetch.s

# target to generate assembly for a file
fetch.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/fetch.cc.s
.PHONY : fetch.cc.s

panda.o: panda.cc.o
.PHONY : panda.o

# target to build an object file
panda.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/panda.cc.o
.PHONY : panda.cc.o

panda.i: panda.cc.i
.PHONY : panda.i

# target to preprocess a source file
panda.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/panda.cc.i
.PHONY : panda.cc.i

panda.s: panda.cc.s
.PHONY : panda.s

# target to generate assembly for a file
panda.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/panda.cc.s
.PHONY : panda.cc.s

python.o: python.cc.o
.PHONY : python.o

# target to build an object file
python.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/python.cc.o
.PHONY : python.cc.o

python.i: python.cc.i
.PHONY : python.i

# target to preprocess a source file
python.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/python.cc.i
.PHONY : python.cc.i

python.s: python.cc.s
.PHONY : python.s

# target to generate assembly for a file
python.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/python.cc.s
.PHONY : python.cc.s

scripts/cpp/com_constraint.o: scripts/cpp/com_constraint.cc.o
.PHONY : scripts/cpp/com_constraint.o

# target to build an object file
scripts/cpp/com_constraint.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/com_constraint.dir/build.make CMakeFiles/com_constraint.dir/scripts/cpp/com_constraint.cc.o
.PHONY : scripts/cpp/com_constraint.cc.o

scripts/cpp/com_constraint.i: scripts/cpp/com_constraint.cc.i
.PHONY : scripts/cpp/com_constraint.i

# target to preprocess a source file
scripts/cpp/com_constraint.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/com_constraint.dir/build.make CMakeFiles/com_constraint.dir/scripts/cpp/com_constraint.cc.i
.PHONY : scripts/cpp/com_constraint.cc.i

scripts/cpp/com_constraint.s: scripts/cpp/com_constraint.cc.s
.PHONY : scripts/cpp/com_constraint.s

# target to generate assembly for a file
scripts/cpp/com_constraint.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/com_constraint.dir/build.make CMakeFiles/com_constraint.dir/scripts/cpp/com_constraint.cc.s
.PHONY : scripts/cpp/com_constraint.cc.s

scripts/cpp/vamp_com_constraint_example.o: scripts/cpp/vamp_com_constraint_example.cc.o
.PHONY : scripts/cpp/vamp_com_constraint_example.o

# target to build an object file
scripts/cpp/vamp_com_constraint_example.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_com_constraint_example.dir/build.make CMakeFiles/vamp_com_constraint_example.dir/scripts/cpp/vamp_com_constraint_example.cc.o
.PHONY : scripts/cpp/vamp_com_constraint_example.cc.o

scripts/cpp/vamp_com_constraint_example.i: scripts/cpp/vamp_com_constraint_example.cc.i
.PHONY : scripts/cpp/vamp_com_constraint_example.i

# target to preprocess a source file
scripts/cpp/vamp_com_constraint_example.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_com_constraint_example.dir/build.make CMakeFiles/vamp_com_constraint_example.dir/scripts/cpp/vamp_com_constraint_example.cc.i
.PHONY : scripts/cpp/vamp_com_constraint_example.cc.i

scripts/cpp/vamp_com_constraint_example.s: scripts/cpp/vamp_com_constraint_example.cc.s
.PHONY : scripts/cpp/vamp_com_constraint_example.s

# target to generate assembly for a file
scripts/cpp/vamp_com_constraint_example.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vamp_com_constraint_example.dir/build.make CMakeFiles/vamp_com_constraint_example.dir/scripts/cpp/vamp_com_constraint_example.cc.s
.PHONY : scripts/cpp/vamp_com_constraint_example.cc.s

sphere.o: sphere.cc.o
.PHONY : sphere.o

# target to build an object file
sphere.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/sphere.cc.o
.PHONY : sphere.cc.o

sphere.i: sphere.cc.i
.PHONY : sphere.i

# target to preprocess a source file
sphere.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/sphere.cc.i
.PHONY : sphere.cc.i

sphere.s: sphere.cc.s
.PHONY : sphere.s

# target to generate assembly for a file
sphere.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/sphere.cc.s
.PHONY : sphere.cc.s

src/impl/vamp/bindings/environment.o: src/impl/vamp/bindings/environment.cc.o
.PHONY : src/impl/vamp/bindings/environment.o

# target to build an object file
src/impl/vamp/bindings/environment.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/src/impl/vamp/bindings/environment.cc.o
.PHONY : src/impl/vamp/bindings/environment.cc.o

src/impl/vamp/bindings/environment.i: src/impl/vamp/bindings/environment.cc.i
.PHONY : src/impl/vamp/bindings/environment.i

# target to preprocess a source file
src/impl/vamp/bindings/environment.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/src/impl/vamp/bindings/environment.cc.i
.PHONY : src/impl/vamp/bindings/environment.cc.i

src/impl/vamp/bindings/environment.s: src/impl/vamp/bindings/environment.cc.s
.PHONY : src/impl/vamp/bindings/environment.s

# target to generate assembly for a file
src/impl/vamp/bindings/environment.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/src/impl/vamp/bindings/environment.cc.s
.PHONY : src/impl/vamp/bindings/environment.cc.s

src/impl/vamp/bindings/settings.o: src/impl/vamp/bindings/settings.cc.o
.PHONY : src/impl/vamp/bindings/settings.o

# target to build an object file
src/impl/vamp/bindings/settings.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/src/impl/vamp/bindings/settings.cc.o
.PHONY : src/impl/vamp/bindings/settings.cc.o

src/impl/vamp/bindings/settings.i: src/impl/vamp/bindings/settings.cc.i
.PHONY : src/impl/vamp/bindings/settings.i

# target to preprocess a source file
src/impl/vamp/bindings/settings.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/src/impl/vamp/bindings/settings.cc.i
.PHONY : src/impl/vamp/bindings/settings.cc.i

src/impl/vamp/bindings/settings.s: src/impl/vamp/bindings/settings.cc.s
.PHONY : src/impl/vamp/bindings/settings.s

# target to generate assembly for a file
src/impl/vamp/bindings/settings.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/src/impl/vamp/bindings/settings.cc.s
.PHONY : src/impl/vamp/bindings/settings.cc.s

ur5.o: ur5.cc.o
.PHONY : ur5.o

# target to build an object file
ur5.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/ur5.cc.o
.PHONY : ur5.cc.o

ur5.i: ur5.cc.i
.PHONY : ur5.i

# target to preprocess a source file
ur5.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/ur5.cc.i
.PHONY : ur5.cc.i

ur5.s: ur5.cc.s
.PHONY : ur5.s

# target to generate assembly for a file
ur5.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_core_ext.dir/build.make CMakeFiles/_core_ext.dir/ur5.cc.s
.PHONY : ur5.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vamp_baxter_stub"
	@echo "... vamp_bimanualpanda_stub"
	@echo "... vamp_fetch_stub"
	@echo "... vamp_panda_stub"
	@echo "... vamp_sphere_stub"
	@echo "... vamp_stub"
	@echo "... vamp_ur5_stub"
	@echo "... _core_ext"
	@echo "... com_constraint"
	@echo "... nanobind-static-abi3"
	@echo "... simdxorshift"
	@echo "... vamp_com_constraint_example"
	@echo "... _deps/nanobind-src/src/common.o"
	@echo "... _deps/nanobind-src/src/common.i"
	@echo "... _deps/nanobind-src/src/common.s"
	@echo "... _deps/nanobind-src/src/error.o"
	@echo "... _deps/nanobind-src/src/error.i"
	@echo "... _deps/nanobind-src/src/error.s"
	@echo "... _deps/nanobind-src/src/implicit.o"
	@echo "... _deps/nanobind-src/src/implicit.i"
	@echo "... _deps/nanobind-src/src/implicit.s"
	@echo "... _deps/nanobind-src/src/nb_enum.o"
	@echo "... _deps/nanobind-src/src/nb_enum.i"
	@echo "... _deps/nanobind-src/src/nb_enum.s"
	@echo "... _deps/nanobind-src/src/nb_ft.o"
	@echo "... _deps/nanobind-src/src/nb_ft.i"
	@echo "... _deps/nanobind-src/src/nb_ft.s"
	@echo "... _deps/nanobind-src/src/nb_func.o"
	@echo "... _deps/nanobind-src/src/nb_func.i"
	@echo "... _deps/nanobind-src/src/nb_func.s"
	@echo "... _deps/nanobind-src/src/nb_internals.o"
	@echo "... _deps/nanobind-src/src/nb_internals.i"
	@echo "... _deps/nanobind-src/src/nb_internals.s"
	@echo "... _deps/nanobind-src/src/nb_ndarray.o"
	@echo "... _deps/nanobind-src/src/nb_ndarray.i"
	@echo "... _deps/nanobind-src/src/nb_ndarray.s"
	@echo "... _deps/nanobind-src/src/nb_static_property.o"
	@echo "... _deps/nanobind-src/src/nb_static_property.i"
	@echo "... _deps/nanobind-src/src/nb_static_property.s"
	@echo "... _deps/nanobind-src/src/nb_type.o"
	@echo "... _deps/nanobind-src/src/nb_type.i"
	@echo "... _deps/nanobind-src/src/nb_type.s"
	@echo "... _deps/nanobind-src/src/trampoline.o"
	@echo "... _deps/nanobind-src/src/trampoline.i"
	@echo "... _deps/nanobind-src/src/trampoline.s"
	@echo "... _deps/simdxorshift-src/src/simdxorshift128plus.o"
	@echo "... _deps/simdxorshift-src/src/simdxorshift128plus.i"
	@echo "... _deps/simdxorshift-src/src/simdxorshift128plus.s"
	@echo "... _deps/simdxorshift-src/src/xorshift128plus.o"
	@echo "... _deps/simdxorshift-src/src/xorshift128plus.i"
	@echo "... _deps/simdxorshift-src/src/xorshift128plus.s"
	@echo "... baxter.o"
	@echo "... baxter.i"
	@echo "... baxter.s"
	@echo "... bimanualpanda.o"
	@echo "... bimanualpanda.i"
	@echo "... bimanualpanda.s"
	@echo "... fetch.o"
	@echo "... fetch.i"
	@echo "... fetch.s"
	@echo "... panda.o"
	@echo "... panda.i"
	@echo "... panda.s"
	@echo "... python.o"
	@echo "... python.i"
	@echo "... python.s"
	@echo "... scripts/cpp/com_constraint.o"
	@echo "... scripts/cpp/com_constraint.i"
	@echo "... scripts/cpp/com_constraint.s"
	@echo "... scripts/cpp/vamp_com_constraint_example.o"
	@echo "... scripts/cpp/vamp_com_constraint_example.i"
	@echo "... scripts/cpp/vamp_com_constraint_example.s"
	@echo "... sphere.o"
	@echo "... sphere.i"
	@echo "... sphere.s"
	@echo "... src/impl/vamp/bindings/environment.o"
	@echo "... src/impl/vamp/bindings/environment.i"
	@echo "... src/impl/vamp/bindings/environment.s"
	@echo "... src/impl/vamp/bindings/settings.o"
	@echo "... src/impl/vamp/bindings/settings.i"
	@echo "... src/impl/vamp/bindings/settings.s"
	@echo "... ur5.o"
	@echo "... ur5.i"
	@echo "... ur5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

